# Generated by Django 5.1.1 on 2024-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consult', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('doctor', models.CharField(max_length=40)),
                ('especialidad', models.CharField(max_length=30)),
                ('horario', models.CharField(max_length=12)),
                ('cita', models.CharField(max_length=40)),
            ],
        ),
    ]
